info:
  contact: {}
paths:
  /api/v1/eth/blocks:
    get:
      consumes:
      - application/json
      parameters:
      - description: return {n} block(s)
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: get eth block list
  /api/v1/eth/blocks/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: the eth block id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: get single eth block with specific id
  /api/v1/eth/transaction/{tx_hash}:
    get:
      consumes:
      - application/json
      parameters:
      - description: eth transaction hash
        in: path
        name: tx_hash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
      summary: get single eth transaction with hash
swagger: "2.0"
