version: "3"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql_data:
    driver: ${VOLUMES_DRIVER}
  mysql_log:
    driver: ${VOLUMES_DRIVER}

services:

  ethereum-node:
    image: ethereum/client-go
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
    networks:
      - backend
    command:
      --http
      --http.addr 0.0.0.0
      --ws
      --ws.addr 0.0.0.0
      --rpcvhosts=*

  mysql:
    build:
      context: ./deployments/mysql/
    volumes:
      - mysql_data:/var/lib/mysql-files
      - mysql_log:/var/log/mysql
    ports:
      - 3306:3306
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend

  redis:
    build:
      context: ./deployments/redis/
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  eth-scanner:
    build:
      context: ./
      args:
        - WORKDIR=/etc/eth-service/cmd/scanner/
    depends_on:
      - ethereum-node
      - mysql
    ports:
      - ${ETH_SERVICE_SERVER_PORT}:${ETH_SERVICE_SERVER_PORT}
    command:
      go run main.go
        --stderrthreshold ${ETH_SERVICE_LOG_LEVEL}
        --run_mode ${ETH_SERVICE_RUN_MODE}
        --database_host ${ETH_SERVICE_DATABASE_HOST}
        --database_port ${ETH_SERVICE_DATABASE_PORT}
        --database_schema ${ETH_SERVICE_DATABASE_SCHEMA}
        --database_username ${ETH_SERVICE_DATABASE_USERNAME}
        --database_password ${ETH_SERVICE_DATABASE_PASSWORD}
        --eth_data_seed_url ${ETH_SERVICE_ETH_DATA_SEED_URL}
    networks:
      - backend

  eth-service:
    build:
      context: ./
      args:
        - WORKDIR=/etc/eth-service/cmd/server/eth/
    depends_on:
      - mysql
      - redis
    ports:
      - ${ETH_SERVICE_SERVER_PORT}:${ETH_SERVICE_SERVER_PORT}
    command:
      go run main.go
        --stderrthreshold ${ETH_SERVICE_LOG_LEVEL}
        --run_mode ${ETH_SERVICE_RUN_MODE}
        --gin_mode ${ETH_SERVICE_GIN_MODE}
        --server_host ${ETH_SERVICE_SERVER_HOST}
        --server_port ${ETH_SERVICE_SERVER_PORT}
        --database_host ${ETH_SERVICE_DATABASE_HOST}
        --database_port ${ETH_SERVICE_DATABASE_PORT}
        --database_schema ${ETH_SERVICE_DATABASE_SCHEMA}
        --database_username ${ETH_SERVICE_DATABASE_USERNAME}
        --database_password ${ETH_SERVICE_DATABASE_PASSWORD}
        --eth_data_seed_url ${ETH_SERVICE_ETH_DATA_SEED_URL}
    networks:
      - backend
